2018-07-07 01:27:06,969 ERROR: Exception on /index [GET] [in /home/kodi/Workspace/parky/venv/lib/python3.6/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/home/kodi/Workspace/parky/venv/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/kodi/Workspace/parky/venv/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/kodi/Workspace/parky/venv/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/kodi/Workspace/parky/venv/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/kodi/Workspace/parky/venv/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/kodi/Workspace/parky/venv/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/kodi/Workspace/parky/venv/lib/python3.6/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/home/kodi/Workspace/parky/app/home/routes.py", line 31, in index
    return render_template('home/index.html', title='Home', posts=posts)
  File "/home/kodi/Workspace/parky/venv/lib/python3.6/site-packages/flask/templating.py", line 135, in render_template
    context, ctx.app)
  File "/home/kodi/Workspace/parky/venv/lib/python3.6/site-packages/flask/templating.py", line 117, in _render
    rv = template.render(context)
  File "/home/kodi/Workspace/parky/venv/lib/python3.6/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/home/kodi/Workspace/parky/venv/lib/python3.6/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/kodi/Workspace/parky/venv/lib/python3.6/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/kodi/Workspace/parky/venv/lib/python3.6/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/home/kodi/Workspace/parky/app/templates/home/index.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/kodi/Workspace/parky/app/templates/base.html", line 15, in top-level template code
    <a href="{{ url_for('index') }}">Home</a>
  File "/home/kodi/Workspace/parky/venv/lib/python3.6/site-packages/flask/helpers.py", line 356, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "/home/kodi/Workspace/parky/venv/lib/python3.6/site-packages/flask/app.py", line 2061, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "/home/kodi/Workspace/parky/venv/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/kodi/Workspace/parky/venv/lib/python3.6/site-packages/flask/helpers.py", line 345, in url_for
    force_external=external)
  File "/home/kodi/Workspace/parky/venv/lib/python3.6/site-packages/werkzeug/routing.py", line 1776, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'index'. Did you mean 'home.index' instead?
2018-07-07 01:31:03,133 INFO: Microblog startup [in /home/kodi/Workspace/parky/app/__init__.py:65]
2018-07-07 01:37:25,987 INFO: Microblog startup [in /home/kodi/Workspace/parky/app/__init__.py:65]
2018-07-07 01:45:18,208 INFO: Microblog startup [in /home/kodi/Workspace/parky/app/__init__.py:65]
2018-07-07 01:45:26,532 INFO: Microblog startup [in /home/kodi/Workspace/parky/app/__init__.py:65]
2018-07-07 01:45:34,395 INFO: Microblog startup [in /home/kodi/Workspace/parky/app/__init__.py:65]
2018-07-07 01:45:39,131 INFO: Microblog startup [in /home/kodi/Workspace/parky/app/__init__.py:65]
2018-07-07 01:45:51,225 ERROR: Exception on /order [GET] [in /home/kodi/Workspace/parky/venv/lib/python3.6/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/home/kodi/Workspace/parky/venv/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/kodi/Workspace/parky/venv/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/kodi/Workspace/parky/venv/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/kodi/Workspace/parky/venv/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/kodi/Workspace/parky/venv/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/kodi/Workspace/parky/venv/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/kodi/Workspace/parky/venv/lib/python3.6/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/home/kodi/Workspace/parky/app/home/routes.py", line 96, in order
    return render_template('home/order/order.html', list=list)
  File "/home/kodi/Workspace/parky/venv/lib/python3.6/site-packages/flask/templating.py", line 134, in render_template
    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/home/kodi/Workspace/parky/venv/lib/python3.6/site-packages/jinja2/environment.py", line 869, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/home/kodi/Workspace/parky/venv/lib/python3.6/site-packages/jinja2/environment.py", line 830, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/home/kodi/Workspace/parky/venv/lib/python3.6/site-packages/jinja2/environment.py", line 804, in _load_template
    template = self.loader.load(self, name, globals)
  File "/home/kodi/Workspace/parky/venv/lib/python3.6/site-packages/jinja2/loaders.py", line 113, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/home/kodi/Workspace/parky/venv/lib/python3.6/site-packages/flask/templating.py", line 58, in get_source
    return self._get_source_fast(environment, template)
  File "/home/kodi/Workspace/parky/venv/lib/python3.6/site-packages/flask/templating.py", line 86, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: home/order/order.html
2018-07-07 01:47:22,940 INFO: Microblog startup [in /home/kodi/Workspace/parky/app/__init__.py:65]
2018-07-07 01:48:10,508 INFO: Microblog startup [in /home/kodi/Workspace/parky/app/__init__.py:65]
2018-07-07 01:49:30,991 INFO: Microblog startup [in /home/kodi/Workspace/parky/app/__init__.py:65]
2018-07-07 13:03:02,665 INFO: Microblog startup [in /home/kodi/Workspace/parky/app/__init__.py:65]
2018-07-07 13:06:17,463 INFO: Microblog startup [in /home/kodi/Workspace/parky/app/__init__.py:65]
